#
# Build and upload AppImage packages
#
name: "AppImage (Beta)"

on: [push]

jobs:
  # AppImage x86_64
  appimage-amd64:
    name: "x86_64"
    runs-on: ubuntu-22.04
    if: "contains(github.event.head_commit.message, '[publish]') || contains(github.ref, 'heads/release')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build AppImage
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        # Update installed packages
        sudo apt remove php7.* -y
        sudo apt remove php8.* -y
        sudo apt update
        # using force-overwrite due to
        # https://github.com/actions/virtual-environments/issues/2703
        sudo ACCEPT_EULA=Y apt upgrade -o Dpkg::Options::="--force-overwrite" --yes
        # Installing dependencies
        sudo apt install -y libgps-dev zlib1g-dev libgl1-mesa-dev libdrm-dev cmake python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot wget
        sudo apt install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools linguist-qt6 libqt6svg6-dev qt6-multimedia-dev libqt6serialport6-dev qt6-positioning-dev libqt6positioning6-plugins libqt6webchannel6-dev libqt6webenginewidgets6 qt6-webengine-dev qt6-webengine-dev-tools libqt6charts6-dev qt6-qpa-plugins
        sudo pip3 install appimage-builder
        sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
        sudo chmod +x /usr/local/bin/appimagetool
        # Prepare to building
        mkdir -p ${{ github.workspace }}/artifact
        mkdir -p ${{ github.workspace }}/builds/appimage
        cd ${{ github.workspace }}/builds/appimage
        export APP_VERSION="edge"
        appimage-builder --recipe ${{ github.workspace }}/util/appimage/stellarium-appimage-qt6-x86_64.yml --skip-test
        cp ${{ github.workspace }}/builds/appimage/*.AppImage ${{ github.workspace }}/artifact

    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: 'Stellarium-edge-qt6-x86_64'
        path: ${{ github.workspace }}/artifact/*.AppImage

